// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/1/2025, 5:35:38 AM
const configMerger = require("/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/plugins/**/*.{js,ts,mjs}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/composables/**/*.{js,ts,mjs}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/utils/**/*.{js,ts,mjs}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/funwiche/Projects/Sites/2025/WAZA/globalmetaltradergmbh.com/app.config.{js,ts,mjs}"] } }));

module.exports = config
